---
- name: Setting devApNsg NSG
  azure_rm_securitygroup: #モジュール名称
    resource_group: "{{ resource_group }}" #リソースグループ
    name: devApNsg #NSG名
    purge_rules: yes
    rules: #NSGに関連付けるルール
      ###############Inbound Rules#####################

      - name: SSH #ルール名
        protocol: Tcp
        destination_port_range: 22
        source_address_prefix:
          - "192.168.0.60/32" #踏み台のみ許可
        access: Allow
        priority: 1001
        direction: Inbound
      - name: http #ルール名
        protocol: Tcp
        destination_port_range: 80
        source_address_prefix:
          - "192.168.0.0/20" #内部からの80番は許容
        access: Allow
        priority: 1002
        direction: Inbound
      - name: intDenyAll
        protocol: "*"
        destination_port_range: "*" #ポート番号の指定
        source_address_prefix:
          - "192.168.0.0/16" #内部全拒否。外部は65500で拒否できる。
        access: Deny
        priority: 4096
        direction: Inbound

      ###############Outbound Rules#####################

      - name: proOutbound
        protocol: Tcp
        destination_port_range: "*"
        destination_address_prefix:
          - "192.168.6.0/23" #PRO
        access: Deny
        priority: 1010
        direction: Outbound
