---
- name: az StorageAccount make
  hosts: localhost # 実行させるグループ
  connection: local # localhostに対してつなげるときの宣言。SSHではなく直接実行する
  vars_files:
    - ./local_vars/{{ resource_group }}/nas.yml
  roles: # 実行させる処理（記載された順番に実行される
    - storage_account
