---
- name: Create NIC
  azure_rm_networkinterface: # Nic作成モジュール
    resource_group: "{{ resource_group }}"
    location: "{{ reasion }}"
    name: "{{ network.nic }}"
    virtual_network: "{{ network.vnet }}"
    subnet: "{{ network.subnet }}"
    public_ip: no
    private_ip_allocation_method: Static
    private_ip_address: "{{ network.private_ip }}"
    security_group: "{{ network.nsg }}"
  delegate_to: localhost

- name: Create VM
  azure_rm_virtualmachine: # VM作成モジュール
    resource_group: "{{ resource_group }}"
    location: "{{ reasion }}"
    name: "{{ machine.name }}"
    vm_size: "{{ machine.size }}"
    network_interface_names: "{{ network.nic }}"
    admin_username: "{{ machine.user }}"
    admin_password: "{{ machine.pass }}"
    os_type: "{{ os.type }}"
    image:
      offer: "{{ os.distribution }}"
      publisher: "{{ os.publisher }}"
      sku: "{{ os.sku }}"
      version: "{{ os.version }}"
    managed_disk_type: "{{ os.disk_type }}"
