---

- name: import config file
  include_vars: ./local_vars/{{ group }}/aks.yml

- name: Create a managed Azure Container Services (AKS) cluster
  azure_rm_aks:
    name: "{{ aks_name }}"
    location: "{{ location }}"
    resource_group: "{{ resource_group }}"
    dns_prefix: "{{ aks_name }}"
    kubernetes_version: "{{ kubernetes_version }}"
    addon:
      virtual_node:
        enabled: yes
        subnet_resource_id: "{{ subnet_resource_id }}"
    linux_profile:
      admin_username: "{{ admin_username }}"
      ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    service_principal:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret }}"
    agent_pool_profiles:
      - name: default
        count: 2
        vm_size: Standard_D2_v2
